# Generated by Django 4.2.21 on 2025-06-24 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='marketing_uploads/', verbose_name='Arquivo')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('file_size', models.BigIntegerField(verbose_name='Tamanho do Arquivo (bytes)')),
                ('file_type', models.CharField(max_length=100, verbose_name='Tipo do Arquivo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('records_processed', models.IntegerField(default=0, verbose_name='Registros Processados')),
                ('records_created', models.IntegerField(default=0, verbose_name='Registros Criados')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Registros Atualizados')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='empresas.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload de Arquivo',
                'verbose_name_plural': 'Uploads de Arquivos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('mes', models.CharField(blank=True, max_length=20, verbose_name='Mês')),
                ('ano', models.IntegerField(blank=True, null=True, verbose_name='Ano')),
                ('semana', models.CharField(blank=True, max_length=10, verbose_name='Semana')),
                ('campaign_name', models.CharField(max_length=200, verbose_name='Nome da Campanha')),
                ('platform', models.CharField(choices=[('google', 'Google Ads'), ('facebook', 'Facebook Ads'), ('instagram', 'Instagram Ads'), ('tiktok', 'TikTok Ads'), ('linkedin', 'LinkedIn Ads'), ('other', 'Outros')], max_length=50, verbose_name='Plataforma')),
                ('clicks', models.IntegerField(default=0, verbose_name='Cliques')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impressões')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo (R$)')),
                ('conversions', models.IntegerField(default=0, verbose_name='Conversões')),
                ('ctr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='CTR (%)')),
                ('cpc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CPC (R$)')),
                ('cpm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CPM (R$)')),
                ('conversion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de Conversão (%)')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='Arquivo Original')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Processado em')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Confiança da IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing_data', to='empresas.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_data_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dado de Marketing',
                'verbose_name_plural': 'Dados de Marketing',
                'ordering': ['-data', 'campaign_name'],
                'unique_together': {('data', 'campaign_name', 'platform', 'empresa')},
            },
        ),
    ]
