# Generated by Django 4.2.21 on 2025-06-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('mes', models.CharField(blank=True, max_length=20, verbose_name='Mês')),
                ('ano', models.IntegerField(blank=True, null=True, verbose_name='Ano')),
                ('semana', models.CharField(blank=True, max_length=10, verbose_name='Semana')),
                ('invest_realizado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invest. Realizado (R$)')),
                ('invest_projetado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Invest. Projetado (R$)')),
                ('saldo_invest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Invest.')),
                ('vendas_google', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vendas Google (R$)')),
                ('vendas_instagram', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vendas Instagram (R$)')),
                ('vendas_facebook', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vendas Facebook (R$)')),
                ('fat_proj', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Faturamento Projetado (R$)')),
                ('fat_camp_realizado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Faturamento Campanha Realizado (R$)')),
                ('fat_geral', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Faturamento Geral (R$)')),
                ('saldo_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo FAT')),
                ('roi_realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ROI Realizado')),
                ('roas_realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='ROAS Realizado')),
                ('cac_realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='CAC Realizado (R$)')),
                ('ticket_medio_realizado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ticket Médio Realizado (R$)')),
                ('arpu_realizado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ARPU Realizado (R$)')),
                ('leads', models.IntegerField(verbose_name='Leads')),
                ('clientes_novos', models.IntegerField(verbose_name='Clientes Novos')),
                ('clientes_recorrentes', models.IntegerField(verbose_name='Clientes Recorrentes')),
                ('conversoes', models.IntegerField(verbose_name='Conversões')),
                ('taxa_conversao', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Taxa de Conversão')),
                ('clima', models.CharField(blank=True, max_length=50, null=True, verbose_name='Clima')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='empresas.empresa')),
            ],
        ),
    ]
