# Generated by Django 4.2.21 on 2025-07-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='clientes_novos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Clientes Novos'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='clientes_recorrentes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Clientes Recorrentes'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='conversoes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Conversões'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='fat_camp_realizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Faturamento Campanha Realizado (R$)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='fat_geral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Faturamento Geral (R$)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='fat_proj',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Faturamento Projetado (R$)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='invest_projetado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Invest. Projetado (R$)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='invest_realizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Invest. Realizado (R$)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='leads',
            field=models.IntegerField(blank=True, null=True, verbose_name='Leads'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='mes',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='semana',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Semana'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='ticket_medio_realizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ticket Médio Realizado (R$)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendas_facebook',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Vendas Facebook (R$)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendas_google',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Vendas Google (R$)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='vendas_instagram',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Vendas Instagram (R$)'),
        ),
    ]
