# Generated by Django 4.2.21 on 2025-06-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='vendas_tiktok',
        ),
    ]
