# Generated by Django 4.2.21 on 2025-07-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0002_alter_venda_clientes_novos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='plataforma',
            field=models.CharField(choices=[('google', 'Google'), ('instagram', 'Instagram'), ('facebook', 'Facebook')], default='google', max_length=20, verbose_name='Plataforma'),
        ),
    ]
