# Generated by Django 5.1.7

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0003_venda_plataforma'),
    ]

    operations = [
        # Índices para campos mais consultados no dashboard
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['empresa', 'ano'], name='venda_empresa_ano_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['empresa', 'ano', 'data'], name='venda_empresa_ano_data_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['empresa', 'vendas_google'], name='venda_empresa_google_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['empresa', 'vendas_instagram'], name='venda_empresa_instagram_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['empresa', 'vendas_facebook'], name='venda_empresa_facebook_idx'),
        ),
        # Índices para campos de agregação
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['empresa', 'ano', 'invest_realizado'], name='venda_empresa_ano_invest_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['empresa', 'ano', 'fat_geral'], name='venda_empresa_ano_fat_idx'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['empresa', 'ano', 'clientes_novos'], name='venda_empresa_ano_clientes_idx'),
        ),
    ]
