# Generated by Django 4.2.21 on 2025-08-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venda', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venda',
            name='venda_empresa_ano_idx',
        ),
        migrations.RemoveIndex(
            model_name='venda',
            name='venda_empresa_ano_data_idx',
        ),
        migrations.RemoveIndex(
            model_name='venda',
            name='venda_empresa_google_idx',
        ),
        migrations.RemoveIndex(
            model_name='venda',
            name='venda_empresa_instagram_idx',
        ),
        migrations.RemoveIndex(
            model_name='venda',
            name='venda_empresa_facebook_idx',
        ),
        migrations.RemoveIndex(
            model_name='venda',
            name='venda_empresa_ano_invest_idx',
        ),
        migrations.RemoveIndex(
            model_name='venda',
            name='venda_empresa_ano_fat_idx',
        ),
        migrations.RemoveIndex(
            model_name='venda',
            name='venda_empresa_ano_clientes_idx',
        ),
    ]
