# Generated by Django 4.2.21 on 2025-08-15 01:44

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=120, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("icone", models.CharField(blank=True, max_length=120, null=True)),
                ("cor", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=16,
                    ),
                ),
                (
                    "criador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categorias_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Influencer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nome_artistico",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("biografia", models.TextField(blank=True, null=True)),
                ("redes_sociais", models.JSONField(blank=True, default=dict)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=16,
                    ),
                ),
                (
                    "comissao_padrao",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=5
                    ),
                ),
                (
                    "categoria_principal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="influencers_principais",
                        to="influencer.categoria",
                    ),
                ),
                (
                    "categorias_secundarias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="influencers_secundarios",
                        to="influencer.categoria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Influencer",
                "verbose_name_plural": "Influencers",
            },
        ),
        migrations.CreateModel(
            name="Loja",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="O nome que aparecerá na URL, ex: seudominio.com/nome-da-loja",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "comissao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=16,
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("configuracoes", models.JSONField(blank=True, default=dict)),
                (
                    "layout_escolhido",
                    models.IntegerField(
                        choices=[
                            (1, "Layout 1"),
                            (2, "Layout 2"),
                            (3, "Layout 3"),
                            (4, "Layout 4"),
                            (5, "Layout 5"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lojas",
                        to="influencer.categoria",
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lojas",
                        to="influencer.influencer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loja",
                "verbose_name_plural": "Lojas",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "link_afiliado",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("imagem_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=16,
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                ("metadados", models.JSONField(blank=True, default=dict)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos",
                        to="influencer.categoria",
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="influencer.influencer",
                    ),
                ),
                (
                    "loja",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos",
                        to="influencer.loja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plataforma",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                            ("twitter", "Twitter"),
                        ],
                        max_length=16,
                    ),
                ),
                ("conteudo", models.TextField()),
                ("data_geracao", models.DateTimeField(auto_now_add=True)),
                ("data_publicacao", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("rascunho", "Rascunho"), ("publicado", "Publicado")],
                        default="rascunho",
                        max_length=16,
                    ),
                ),
                ("metricas", models.JSONField(blank=True, default=dict)),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="influencer.influencer",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="influencer.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-data_geracao"],
            },
        ),
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cliente_nome", models.CharField(max_length=150)),
                ("cliente_email", models.EmailField(max_length=254)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "preco_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "comissao",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("data_venda", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendente",
                        max_length=16,
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[("manual", "Manual"), ("api", "API")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas",
                        to="influencer.influencer",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas",
                        to="influencer.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "indexes": [
                    models.Index(
                        fields=["data_venda"], name="influencer__data_ve_770dc0_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(fields=["nome"], name="influencer__nome_d70b10_idx"),
        ),
        migrations.AddConstraint(
            model_name="loja",
            constraint=models.UniqueConstraint(
                fields=("influencer", "nome"), name="unique_loja_por_influencer_nome"
            ),
        ),
        migrations.AddIndex(
            model_name="influencer",
            index=models.Index(
                fields=["usuario"], name="influencer__usuario_27cb6d_idx"
            ),
        ),
    ]
