# Generated by Django 4.2.21 on 2025-08-15 23:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("influencer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LojaParceira",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("url", models.URLField(max_length=500)),
                (
                    "comissao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=16,
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lojas_parceiras",
                        to="influencer.categoria",
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lojas_parceiras",
                        to="influencer.influencer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loja Parceira",
                "verbose_name_plural": "Lojas Parceiras",
                "ordering": ["-data_cadastro"],
            },
        ),
    ]
