# Generated by Django 4.2.21 on 2025-08-16 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("influencer", "0002_lojaparceira"),
    ]

    operations = [
        migrations.AddField(
            model_name="lojaparceira",
            name="logo_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="produto",
            name="loja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produtos",
                to="influencer.lojaparceira",
            ),
        ),
    ]
