# Generated by Django 4.2.21 on 2025-08-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("influencer", "0003_lojaparceira_logo_url_alter_produto_loja"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="imagem_url",
        ),
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="produtos/"),
        ),
    ]
