# Generated by Django 4.2.21 on 2025-08-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("influencer", "0004_remove_produto_imagem_url_produto_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="lojaparceira",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
