# Generated by Django 4.2.21 on 2025-08-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("influencer", "0005_lojaparceira_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lojaparceira",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="influencer/logoloja/"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="influencer/produtos/"
            ),
        ),
    ]
