# Generated by Django 4.2.21 on 2025-08-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("influencer", "0006_alter_lojaparceira_logo_alter_produto_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="loja",
            name="banner_layout",
            field=models.ImageField(
                blank=True, null=True, upload_to="influencer/layout/banners/"
            ),
        ),
        migrations.AddField(
            model_name="loja",
            name="logo_layout",
            field=models.ImageField(
                blank=True, null=True, upload_to="influencer/layout/logos/"
            ),
        ),
    ]
