# Generated by Django 4.2.21 on 2025-08-16 02:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("influencer", "0007_loja_banner_layout_loja_logo_layout"),
    ]

    operations = [
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tipo_clique",
                    models.CharField(
                        choices=[
                            ("produto_comprar", "Clique Comprar Agora (Produto)"),
                            ("loja_destaque", "Clique em Loja (Destaque)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliques",
                        to="influencer.influencer",
                    ),
                ),
                (
                    "loja_parceira",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliques",
                        to="influencer.lojaparceira",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliques",
                        to="influencer.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clique",
                "verbose_name_plural": "Cliques",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["produto"], name="influencer__produto_73b656_idx"
                    ),
                    models.Index(
                        fields=["loja_parceira"], name="influencer__loja_pa_4ee263_idx"
                    ),
                ],
            },
        ),
    ]
