# Generated by Django 4.2.21 on 2025-08-20 16:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("influencer", "0008_click"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitaInfluencer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("referer", models.URLField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("data_visita", models.DateTimeField(auto_now_add=True)),
                ("data_visita_date", models.DateField(auto_now_add=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitas",
                        to="influencer.influencer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita de Influencer",
                "verbose_name_plural": "Visitas de Influencer",
                "ordering": ["-data_visita"],
                "indexes": [
                    models.Index(
                        fields=["influencer", "data_visita"],
                        name="influencer__influen_4acbe1_idx",
                    ),
                    models.Index(
                        fields=["data_visita_date"],
                        name="influencer__data_vi_5bffd0_idx",
                    ),
                    models.Index(
                        fields=["influencer", "data_visita_date"],
                        name="influencer__influen_628449_idx",
                    ),
                ],
            },
        ),
    ]
