# Generated by Django 4.2.21 on 2025-08-30 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("influencer", "0009_visitainfluencer"),
    ]

    operations = [
        migrations.AddField(
            model_name="loja",
            name="profile_layout",
            field=models.ImageField(
                blank=True, null=True, upload_to="influencer/layout/profiles/"
            ),
        ),
    ]
