# Generated by Django 4.2.21 on 2025-06-24 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('inactive', 'Inativo')], default='pending', max_length=10, verbose_name='Status')),
                ('permissions', models.JSONField(default=dict, verbose_name='Permissões')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_links', to='empresas.empresa', verbose_name='Empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vínculo Usuário-Empresa',
                'verbose_name_plural': 'Vínculos Usuário-Empresa',
                'unique_together': {('user', 'empresa')},
            },
        ),
    ]
