# Generated by Django 4.2.21 on 2025-06-29 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0003_empresa_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario_criado', 'Usuário PF Criado'), ('empresa_criada', 'Empresa Criada'), ('plano_expirado', 'Plano Expirado'), ('plano_renovado', 'Plano Renovado'), ('empresa_bloqueada', 'Empresa Bloqueada'), ('empresa_ativada', 'Empresa Ativada'), ('pagamento_recebido', 'Pagamento Recebido'), ('assinatura_criada', 'Assinatura Criada'), ('assinatura_cancelada', 'Assinatura Cancelada'), ('sistema', 'Sistema')], help_text='Tipo da notificação', max_length=20, verbose_name='Tipo')),
                ('titulo', models.CharField(help_text='Título da notificação', max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(help_text='Mensagem detalhada da notificação', verbose_name='Mensagem')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', help_text='Prioridade da notificação', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('nao_lida', 'Não Lida'), ('lida', 'Lida'), ('arquivada', 'Arquivada')], default='nao_lida', help_text='Status da notificação', max_length=10, verbose_name='Status')),
                ('dados_extras', models.JSONField(blank=True, help_text='Dados adicionais da notificação', null=True, verbose_name='Dados Extras')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data de criação da notificação', verbose_name='Criado em')),
                ('lida_em', models.DateTimeField(blank=True, help_text='Data em que a notificação foi lida', null=True, verbose_name='Lida em')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_admin', to='empresas.empresa', verbose_name='Empresa Relacionada')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_admin', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Relacionado')),
            ],
            options={
                'verbose_name': 'Notificação Admin',
                'verbose_name_plural': 'Notificações Admin',
                'ordering': ['-criado_em'],
            },
        ),
    ]
