# Generated by Django 4.2.21 on 2025-08-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_login_completed",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o usuário já completou sua primeira sessão no sistema",
                verbose_name="Primeiro Login Completo",
            ),
        ),
    ]
