# Generated by Django 4.2.21 on 2025-08-18 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_first_login_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o email do usuário foi verificado",
                verbose_name="Email Verificado",
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código de verificação de 6 dígitos",
                        max_length=6,
                        verbose_name="Código",
                    ),
                ),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("registration", "Confirmação de Registro"),
                            ("password_reset", "Recuperação de Senha"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Código",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o código já foi utilizado",
                        verbose_name="Usado",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de Verificação de Email",
                "verbose_name_plural": "Códigos de Verificação de Email",
                "ordering": ["-created_at"],
            },
        ),
    ]
