# Generated by Django 4.2.21 on 2025-08-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_email_verified_emailverificationcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverificationcode",
            name="code",
            field=models.CharField(
                help_text="Código numérico de 6 dígitos",
                max_length=6,
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="emailverificationcode",
            name="is_used",
            field=models.BooleanField(
                default=False,
                help_text="Marca o código como utilizado",
                verbose_name="Usado",
            ),
        ),
    ]
