# Generated by Django 4.2.21 on 2025-08-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_emailverificationcode_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("PF", "Pessoa Física"),
                    ("PJ", "Pessoa Jurídica"),
                    ("PFE", "Pessoa Física Empresarial"),
                ],
                help_text="Tipo de usuário (PF, PJ ou PFE)",
                max_length=3,
                verbose_name="Tipo de Usuário",
            ),
        ),
    ]
