# Generated by Django 4.2.21 on 2025-08-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms_accepted",
            field=models.BooleanField(
                default=False,
                help_text="Indica se o usuário aceitou os termos de uso vigentes no momento do cadastro",
                verbose_name="Termos aceitos",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data/hora do aceite dos termos de uso",
                null=True,
                verbose_name="Termos aceitos em",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_version",
            field=models.CharField(
                blank=True,
                help_text="Versão dos termos de uso aceitos",
                max_length=20,
                null=True,
                verbose_name="Versão dos Termos",
            ),
        ),
    ]
