# Generated by Django 4.2.21 on 2025-06-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAssinaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_gratis_trial', models.PositiveIntegerField(default=7)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Assinaturas',
                'verbose_name_plural': 'Configurações de Assinaturas',
            },
        ),
    ]
