# Generated by Django 4.2.21 on 2025-06-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas', '0002_configuracaoassinaturas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracaoAssinaturas',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações sobre a assinatura', null=True),
        ),
    ]
