# Generated by Django 4.2.21 on 2025-06-28 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assinaturas', '0003_delete_configuracaoassinaturas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CRIACAO', 'Criação'), ('ATIVACAO', 'Ativação'), ('EXPIRACAO', 'Expiração'), ('REATIVACAO', 'Reativação'), ('TROCA_PLANO', 'Troca de Plano'), ('EXTENSAO', 'Extensão de Prazo'), ('BLOQUEIO', 'Bloqueio'), ('DESBLOQUEIO', 'Desbloqueio'), ('CANCELAMENTO', 'Cancelamento')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_inicio_anterior', models.DateTimeField(blank=True, null=True)),
                ('data_fim_anterior', models.DateTimeField(blank=True, null=True)),
                ('data_inicio_nova', models.DateTimeField(blank=True, null=True)),
                ('data_fim_nova', models.DateTimeField(blank=True, null=True)),
                ('dias_adicional', models.PositiveIntegerField(blank=True, help_text='Dias adicionados na extensão', null=True)),
                ('valor_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_novo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='assinaturas.assinatura')),
                ('plano_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_anterior', to='assinaturas.plano')),
                ('plano_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_novo', to='assinaturas.plano')),
                ('usuario_admin', models.ForeignKey(blank=True, help_text='Admin que fez a alteração', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Pagamento',
                'verbose_name_plural': 'Históricos de Pagamento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
