# Generated by Django 4.2.21 on 2025-08-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assinaturas", "0004_historicopagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="assinatura",
            name="asaas_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="assinatura",
            name="asaas_subscription_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="assinatura",
            name="next_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assinatura",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendente"),
                    ("CONFIRMED", "Confirmado"),
                    ("OVERDUE", "Em Atraso"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assinatura",
            name="trial_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plano",
            name="asaas_price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plano",
            name="asaas_product_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="plano",
            name="auto_renew",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plano",
            name="trial_days",
            field=models.PositiveIntegerField(default=7),
        ),
    ]
