# Generated by Django 4.2.21 on 2025-08-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assinaturas", "0005_assinatura_asaas_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plano",
            name="acesso_analytics",
            field=models.BooleanField(
                default=True, help_text="Acesso ao módulo de analytics"
            ),
        ),
        migrations.AddField(
            model_name="plano",
            name="acesso_api",
            field=models.BooleanField(default=False, help_text="Acesso à API"),
        ),
        migrations.AddField(
            model_name="plano",
            name="acesso_configuracoes",
            field=models.BooleanField(
                default=True, help_text="Acesso ao módulo de configurações"
            ),
        ),
        migrations.AddField(
            model_name="plano",
            name="acesso_financeiro",
            field=models.BooleanField(
                default=True, help_text="Acesso ao módulo financeiro"
            ),
        ),
        migrations.AddField(
            model_name="plano",
            name="acesso_influencer",
            field=models.BooleanField(
                default=False, help_text="Acesso ao módulo influencer"
            ),
        ),
        migrations.AddField(
            model_name="plano",
            name="acesso_marketing",
            field=models.BooleanField(
                default=True, help_text="Acesso ao módulo de marketing"
            ),
        ),
        migrations.AddField(
            model_name="plano",
            name="acesso_relatorios",
            field=models.BooleanField(
                default=False, help_text="Acesso ao módulo de relatórios"
            ),
        ),
        migrations.AddField(
            model_name="plano",
            name="acesso_suporte_prioritario",
            field=models.BooleanField(default=False, help_text="Suporte prioritário"),
        ),
        migrations.AddField(
            model_name="plano",
            name="acesso_usuarios",
            field=models.BooleanField(
                default=True, help_text="Acesso ao módulo de usuários"
            ),
        ),
        migrations.AddField(
            model_name="plano",
            name="acesso_white_label",
            field=models.BooleanField(default=False, help_text="Acesso ao white label"),
        ),
    ]
