# Generated by Django 4.2.21 on 2025-08-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assinaturas", "0006_plano_acesso_analytics_plano_acesso_api_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plano",
            name="descricao",
            field=models.TextField(
                blank=True, help_text="Descrição detalhada do plano", null=True
            ),
        ),
        migrations.AddField(
            model_name="plano",
            name="desvantagens",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de limitações do plano (ex: ['Máximo 100 produtos', 'Sem API'])",
            ),
        ),
        migrations.AddField(
            model_name="plano",
            name="vantagens",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de vantagens do plano (ex: ['Suporte 24/7', 'Analytics avançados'])",
            ),
        ),
    ]
