# Generated by Django 4.2.21 on 2025-08-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assinaturas", "0007_plano_descricao_plano_desvantagens_plano_vantagens"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assinatura",
            index=models.Index(
                fields=["empresa", "ativa", "expirada"], name="assin_empresa_ativa_exp"
            ),
        ),
        migrations.AddIndex(
            model_name="assinatura",
            index=models.Index(
                fields=["asaas_subscription_id"], name="assin_asaas_sub_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assinatura",
            index=models.Index(fields=["payment_status"], name="assin_pay_status_idx"),
        ),
        migrations.AddIndex(
            model_name="assinatura",
            index=models.Index(fields=["fim"], name="assin_fim_idx"),
        ),
    ]
