# Generated by Django 4.2.21 on 2025-08-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsaasWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SUBSCRIPTION_CREATED", "Assinatura Criada"),
                            ("SUBSCRIPTION_ACTIVATED", "Assinatura Ativada"),
                            ("SUBSCRIPTION_CANCELLED", "Assinatura Cancelada"),
                            ("SUBSCRIPTION_DELETED", "Assinatura Deletada"),
                            ("SUBSCRIPTION_UPDATED", "Assinatura Atualizada"),
                            ("SUBSCRIPTION_INACTIVATED", "Assinatura Inativada"),
                            ("PAYMENT_RECEIVED", "Pagamento Recebido"),
                            ("PAYMENT_OVERDUE", "Pagamento em Atraso"),
                            ("PAYMENT_DELETED", "Pagamento Deletado"),
                            ("PAYMENT_CONFIRMED", "Pagamento Confirmado"),
                        ],
                        help_text="Tipo do evento recebido do Asaas",
                        max_length=50,
                        verbose_name="Tipo do Evento",
                    ),
                ),
                (
                    "asaas_id",
                    models.CharField(
                        help_text="ID único do evento no Asaas",
                        max_length=100,
                        verbose_name="ID do Asaas",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Dados completos recebidos do webhook",
                        verbose_name="Dados do Webhook",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("processed", "Processado"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        help_text="Status do processamento do webhook",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Mensagem de erro se o processamento falhou",
                        null=True,
                        verbose_name="Mensagem de Erro",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora em que foi processado",
                        null=True,
                        verbose_name="Processado em",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data/hora de criação do registro",
                        verbose_name="Criado em",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Asaas",
                "verbose_name_plural": "Webhooks Asaas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type"], name="asaas_asaas_event_t_aad413_idx"
                    ),
                    models.Index(
                        fields=["status"], name="asaas_asaas_status_8a053d_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="asaas_asaas_created_b0dbfb_idx"
                    ),
                ],
            },
        ),
    ]
