# Generated by Django 4.2.21 on 2025-08-11 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("asaas", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="asaaswebhook",
            new_name="webhook_event_idx",
            old_name="asaas_asaas_event_t_aad413_idx",
        ),
        migrations.RenameIndex(
            model_name="asaaswebhook",
            new_name="webhook_status_idx",
            old_name="asaas_asaas_status_8a053d_idx",
        ),
        migrations.RenameIndex(
            model_name="asaaswebhook",
            new_name="webhook_created_idx",
            old_name="asaas_asaas_created_b0dbfb_idx",
        ),
    ]
