# Generated by Django 4.2.21 on 2025-08-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulopermissao',
            name='codigo',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('financeiro', 'Financeiro'), ('influencer', 'Influencer')], max_length=50, unique=True, verbose_name='Código do Módulo'),
        ),
    ]
