# Generated by Django 4.2.21 on 2025-06-24 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_convidado', models.EmailField(help_text='Email do usuário PF convidado', max_length=254, verbose_name='Email do Convidado')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('rejected', 'Recusado'), ('expired', 'Expirado')], default='pending', help_text='Status atual do convite', max_length=10, verbose_name='Status')),
                ('data_envio', models.DateTimeField(auto_now_add=True, help_text='Data em que o convite foi enviado', verbose_name='Data de Envio')),
                ('data_resposta', models.DateTimeField(blank=True, help_text='Data em que o convite foi respondido', null=True, verbose_name='Data de Resposta')),
                ('data_expiracao', models.DateTimeField(blank=True, help_text='Data em que o convite expira', null=True, verbose_name='Data de Expiração')),
                ('convidado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Convidado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Convite de Usuário',
                'verbose_name_plural': 'Convites de Usuários',
                'ordering': ['-data_envio'],
            },
        ),
    ]
