# Generated by Django 4.2.21 on 2025-06-02 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], max_length=2)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=100, null=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('inscricao_municipal', models.CharField(blank=True, max_length=20, null=True)),
                ('registro_crmv_uf', models.CharField(blank=True, max_length=2, null=True)),
                ('registro_crmv_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('email_comercial', models.EmailField(max_length=254)),
                ('telefone1', models.CharField(max_length=15)),
                ('telefone2', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone3', models.CharField(blank=True, max_length=15, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('redes_sociais', models.JSONField(default=list)),
                ('horario_funcionamento', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuso_horario', models.CharField(max_length=50)),
                ('info_idade_cliente', models.CharField(choices=[('aniversario', 'Somente aniversário'), ('nascimento', 'Data de nascimento')], max_length=20)),
                ('arquivar_ficha_automatico', models.BooleanField(default=False)),
                ('bloqueio_eventos_clinicos', models.CharField(choices=[('nao_bloquear', 'Não bloquear'), ('1_hora', '1 hora após a inclusão'), ('2_horas', '2 horas após a inclusão'), ('6_horas', '6 horas após a inclusão'), ('8_horas', '8 horas após a inclusão'), ('12_horas', '12 horas após a inclusão'), ('1_dia', '1 dia após a inclusão'), ('2_dias', '2 dias após a inclusão'), ('3_dias', '3 dias após a inclusão'), ('7_dias', '7 dias após a inclusão'), ('14_dias', '14 dias após a inclusão'), ('21_dias', '21 dias após a inclusão'), ('30_dias', '30 dias após a inclusão')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Logomarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='logomarcas/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logomarca', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('ponto_referencia', models.CharField(blank=True, max_length=200, null=True)),
                ('geolocalizacao', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('admin', 'Administrador'), ('financeiro', 'Financeiro')], max_length=20)),
                ('emails_financeiro', models.JSONField(default=list)),
                ('celular_financeiro', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsaveis', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('empresa', 'tipo')},
            },
        ),
    ]
