# Generated by Django 4.2.21 on 2025-06-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_nome_fantasia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parametros',
        ),
    ]
