# Generated by Django 4.2.21 on 2025-08-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresas", "0003_empresa_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="asaas_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
