# Generated by Django 4.2.21 on 2025-06-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_delete_parametros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='registro_crmv_numero',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='registro_crmv_uf',
        ),
    ]
