# Generated by Django 4.2.21 on 2025-06-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_remove_empresa_registro_crmv_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='telefone3',
        ),
    ]
